channels:
  - simpleitk
  - conda-forge
  - anaconda
dependencies:
  - python==3.10
  - numpy==1.23
  - h5py==3.8
  - matplotlib==3.7
  - simpleitk==2.2
  - hdf5storage==0.1.19
  - scikit-image==0.20
  - numba==0.56.4
  - pandas==2.0.1
  - pymaxflow==1.3.0
  - py-opencv==4.6.0
  - pip
  - pip:
    - git+https://github.com/BMRRgroup/2echo-WaterFat-hmrGC.git
